services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "4056:5678"
    volumes:
      - ./n8n/data:/home/node/.n8n
    environment:
      - DB_TYPE=postgres
      - DB_POSTGRESDB_HOST=n8n-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_URL=http://localhost:4056
      - GENERIC_TIMEZONE=UTC
      - TZ=UTC
    depends_on:
      - n8n-db
    networks:
      - n8n_network

  n8n-db:
    image: postgres:15
    container_name: n8n-db
    restart: unless-stopped
    ports:
      - "5440:5432"
    volumes:
      - ./n8n/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - TZ=UTC
    networks:
      - n8n_network

volumes:
  n8n_data:
  n8n_db:

networks:
  n8n_network:
    driver: bridge 
