
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "4024:80"
    environment:
      DOMAIN: http://localhost:4024
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: your_admin_token_here
      SMTP_HOST: 
      SMTP_FROM: 
      SMTP_PORT: 587
      SMTP_SSL: true
      SMTP_USERNAME: 
      SMTP_PASSWORD: 
      SMTP_AUTH_MECHANISM: Login
      SHOW_PASSWORD_HINT: false
      WEB_VAULT_ENABLED: true
      WEB_VAULT_FILES: /web-vault/
    volumes:
      - ./data:/data
      - ./web-vault:/web-vault
    networks:
      - vaultwarden-network

networks:
  vaultwarden-network:
    driver: bridge 
