
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "4026:3000"
      - "222:22"
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - TZ=UTC
    depends_on:
      - gitea-db
    networks:
      - gitea-network

  gitea-db:
    image: postgres:15
    container_name: gitea-db
    restart: unless-stopped
    ports:
      - "5437:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - TZ=UTC
    networks:
      - gitea-network

networks:
  gitea-network:
    driver: bridge 
