
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - ./config:/config
      - ./books:/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - CALIBRE_DBPATH=/books
      - CALIBRE_CONFIG_DIRECTORY=/config/calibre
    networks:
      - calibre_network

  calibre-server:
    image: linuxserver/calibre:latest
    container_name: calibre-server
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "8082:8081"
    volumes:
      - ./config:/config
      - ./books:/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - CLI_ARGS=--enable-local-write
    networks:
      - calibre_network

networks:
  calibre_network:
    driver: bridge

volumes:
  calibre_config:
  calibre_books: 
