
services:
  graylog:
    image: graylog/graylog:latest
    container_name: graylog
    restart: unless-stopped
    ports:
      - "4040:9000"
      - "12201:12201/udp"
      - "1514:1514"
    volumes:
      - ./data:/usr/share/graylog/data
    environment:
      - GRAYLOG_PASSWORD_SECRET=your-password-secret
      - GRAYLOG_ROOT_PASSWORD_SHA2=your-root-password-sha2
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:4040/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://graylog-elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://graylog-mongodb:27017/graylog
      - TZ=UTC
    depends_on:
      - graylog-mongodb
      - graylog-elasticsearch
    networks:
      - graylog-network

  graylog-mongodb:
    image: mongo:6
    container_name: graylog-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - TZ=UTC
    networks:
      - graylog-network

  graylog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: graylog-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=UTC
    networks:
      - graylog-network

networks:
  graylog-network:
    driver: bridge 
