
services:
  wekan:
    image: wekan/wekan:latest
    container_name: wekan
    restart: unless-stopped
    ports:
      - "4031:8080"
    volumes:
      - ./data:/data
    environment:
      - ROOT_URL=http://localhost:4031
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - TZ=UTC
    depends_on:
      - wekan-db
    networks:
      - wekan-network

  wekan-db:
    image: mongo:6
    container_name: wekan-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    environment:
      - TZ=UTC
    networks:
      - wekan-network

networks:
  wekan-network:
    driver: bridge 
