
services:
  kiwix-serve:
    image: kiwix/kiwix-serve:latest
    container_name: kiwix-serve
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./library:/library
    environment:
      - TZ=UTC
    command: >
      --library /library/library.xml
      --port 8080
      --address 0.0.0.0
      --verbose
    networks:
      - kiwix_network

  kiwix-tools:
    image: kiwix/kiwix-tools:latest
    container_name: kiwix-tools
    restart: "no"
    volumes:
      - ./data:/data
      - ./library:/library
      - ./downloads:/downloads
    environment:
      - TZ=UTC
    networks:
      - kiwix_network

networks:
  kiwix_network:
    driver: bridge

volumes:
  kiwix_data:
  kiwix_library:
  kiwix_downloads: 
